---
title: "Mapping in R"
editor: source
---

```{r map-opts, echo=FALSE}
knitr::opts_chunk$set(
  comment = "R>", 
  warning = FALSE, 
  message = FALSE,
  eval = FALSE
)
```

Yesterday we learned how to create **`ggplot2`** figures, change their aesthetics, labels, colour palettes, and facet/arrange them. Now we are going to look at how to create maps. 

Most of the work that we perform as environmental/biological scientists involves going out to a location and sampling information there. Sometimes only once, and sometimes over a period of time. All of these different sampling methods lend themselves to different types of figures. One of those, collection of data at different points, is best shown with maps. As we will see over the course of Day 3, creating maps in **`ggplot2`** is very straight forward and is extensively supported. For that reason we are going to have plenty of time to also learn how to do some more advanced things. 

## Slides and application exercises

::: slide-deck
**Mapping 1: Basics**

::: slides
[Slides](https://face-it-project.github.io/R_workshop/course_material/_slides/maps_1_basics.html)
:::

::: source
[Source](https://github.com/FACE-IT-project/R_workshop/tree/main/course_material/_slides/maps_1_basics.qmd)
:::
:::

::: application-exercise
**The current landscape.**

::: source
[Source](https://github.com/FACE-IT-project/R_workshop/tree/main/course_material/exercises/maps_1_basics.R)
:::
:::

::: slide-deck
**Mapping 2: Style**

::: slides
[Slides](https://face-it-project.github.io/R_workshop/course_material/_slides/maps_2_style.html)
:::

::: source
[Source](https://github.com/FACE-IT-project/R_workshop/tree/main/course_material/_slides/maps_2_style.qmd)
:::
:::

::: application-exercise
**Here there be dragons.**

::: source
[Source](https://github.com/FACE-IT-project/R_workshop/tree/main/course_material/exercises/maps_2_style.R)
<!-- BONUS: add images to map. -->
:::
:::

::: slide-deck
**Mapping 3: Arctic**

::: slides
[Slides](https://face-it-project.github.io/R_workshop/course_material/_slides/maps_3_Arctic.html)
:::

::: source
[Source](https://github.com/FACE-IT-project/R_workshop/tree/main/course_material/_slides/maps_3_Arctic.qmd)
:::
:::

::: application-exercise
**A polar-ising subject.**

::: source
[Source](https://github.com/FACE-IT-project/R_workshop/tree/main/course_material/exercises/maps_3_Arctic.R)
:::
:::

## DIY maps

Now that we have learned how to make conventional maps, as well as polar projections, it is time for us to branch out once again at let our creative juices flow. Please group up as you see fit and create your own beautiful map of wherever you like. Bonus points for faceting in additional figures showing supplementary information. Feel free to use either conventional maps or the polar alternative. Same as yesterday, we will be walking the room to help with any issues that may arise.

